def exercise_list
  return [
    {name: "Barbell Back Squats", unilateral: false, machine: false, bodyweight: true},
    {name: "Barbell Biceps Curls ~0°", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Biceps Curls Preacher/Supported", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Clean and Jerks", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Cleans", unilateral: false, machine: false, bodyweight: true},
    {name: "Barbell Dead Lifts", unilateral: false, machine: false, bodyweight: true},
    {name: "Barbell Decline Bench Press - Low", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Flat Bench Press", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Front Squats", unilateral: false, machine: false, bodyweight: true},
    {name: "Barbell Hammer Curls", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Horizontal Rows", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Incline Bench Press - Low", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Incline Bench Press ~45°", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Incline Bench Press - High", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Jerks", unilateral: false, machine: false, bodyweight: true},
    {name: "Barbell Narrow Stance Back Squats", unilateral: false, machine: false, bodyweight: true},
    {name: "Barbell Narrow Stance Front Squats", unilateral: false, machine: false, bodyweight: true},
    {name: "Barbell Overhead Press", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Preacher/Supported Biceps Curls", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Shoulder Shrugs", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Stiff Legged Dead Lifts", unilateral: false, machine: false, bodyweight: true},
    {name: "Barbell Sumo Dead Lifts", unilateral: false, machine: false, bodyweight: true},
    {name: "Barbell Triceps Extensions  ~90°", unilateral: false, machine: false, bodyweight: false},
    {name: "Barbell Walking Lunges", unilateral: false, machine: false, bodyweight: true},
    {name: "Bodyweight Dips", unilateral: false, machine: false, bodyweight: true},
    {name: "Bodyweight Dips Plus Weight", unilateral: false, machine: false, bodyweight: true},
    {name: "Bodyweight Jump Lunges", unilateral: false, machine: false, bodyweight: true},
    {name: "Bodyweight Squats Unilateral", unilateral: true, machine: false, bodyweight: true},
    {name: "Bodyweight Pull-ups Plus Weight", unilateral: false, machine: false, bodyweight: true},
    {name: "Bodyweight Pull-ups", unilateral: false, machine: false, bodyweight: true},
    {name: "Bodyweight Push-ups", unilateral: false, machine: false, bodyweight: true},
    {name: "Bodyweight Squats", unilateral: false, machine: false, bodyweight: true},
    {name: "Bodyweight Chin-ups", unilateral: false, machine: false, bodyweight: true},
    {name: "Bodyweight Chin-ups[underhand] Plus Weight", unilateral: false, machine: false, bodyweight: true},
    {name: "Bodyweight Triangle Push-ups", unilateral: false, machine: false, bodyweight: true},
    {name: "Bodyweight Walking Lunges", unilateral: false, machine: false, bodyweight: true},
    {name: "Bodyweight Push-ups Wide", unilateral: false, machine: false, bodyweight: true},
    {name: "Cable Biceps Curls ~0°", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Biceps Curls ~45°", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Biceps Curls ~90°", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Shoulder Front Raises", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Biceps Hammer Curls", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Horizontal Rows Unilateral", unilateral: true, machine: false, bodyweight: false},
    {name: "Cable Horizontal Rows - Underhanded", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Horizontal Rows - Parallel-grip", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Pulldowns Parallel-grip Narrow", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Pulldowns Parallel-grip Wide", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Pulldowns Underhanded", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Pulldowns", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Tricep Extensions Reverse Grip Unilateral", unilateral: true, machine: false, bodyweight: false},
    {name: "Cable Tricep Extensions Reverse Grip", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Shoulder Raises ~0°", unilateral: true, machine: false, bodyweight: false},
    {name: "Cable Shoulder Raises ~45°", unilateral: true, machine: false, bodyweight: false},
    {name: "Cable Triceps Extensions  ~0°", unilateral: false, machine: false, bodyweight: false},
    {name: "Cable Triceps Extensions  ~90°", unilateral: false, machine: false, bodyweight: false},
    {name: "Crossover Reverse Flies", unilateral: true, machine: false, bodyweight: false},
    {name: "Crossover Shoulder Raises ~0°", unilateral: true, machine: false, bodyweight: false},
    {name: "Crossover Shoulder Raises ~45°", unilateral: true, machine: false, bodyweight: false},
    {name: "Crossover 'Y' Pulldowns", unilateral: true, machine: false, bodyweight: false},
    {name: "Crossover Butterflies", unilateral: true, machine: false, bodyweight: false},
    {name: "Crossover Butterflies Incline", unilateral: true, machine: false, bodyweight: false},
    {name: "Crossover Decline Bench Press", unilateral: true, machine: false, bodyweight: false},
    {name: "Crossover Flat Bench Press", unilateral: true, machine: false, bodyweight: false},
    {name: "Crossover Incline Bench Press", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Biceps Curls", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Biceps Curls Reclined", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Butterflies", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Dead Lifts", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Decline Bench Press - Low", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Flat Bench Press", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Front Raises", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Front Squats", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Hammer Biceps Curls", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Horizontal Rows", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Incline Bench Press - Low", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Incline Bench Press ~45°", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Incline Bench Press - High", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Jump Lunges", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Shoulder Press", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Preacher/Supported Biceps Curls", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Shoulder Raises", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Shoulder Shrugs", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Squats", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Stiff Legged Dead Lifts", unilateral: true, machine: false, bodyweight: false},
    {name: "Lying Triceps Extensions", unilateral: true, machine: false, bodyweight: false},
    {name: "Dumbbell Walking Lunges", unilateral: true, machine: false, bodyweight: false},
    {name: "Machine Bent Leg Calf Raises", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Bicep Curls Unsupported Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Bicep Curls Supported Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Bicep Curls Reclined Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Biceps Curls Unsupported", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Biceps Curls Supported", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Biceps Curls Reclined", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Flies", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Dips", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Flat Bench Press Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Flat Bench Press", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Glute Kick-backs Unilateral", unilateral: true, machine: true, bodyweight: false},
    {name: "Machine Horizontal Rows Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Horizontal Rows", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Incline Bench Press Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Incline Bench Press", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Leg Abductions", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Leg Adductions", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Leg Extensions Unilateral", unilateral: true, machine: true, bodyweight: false},
    {name: "Machine Leg Extensions", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Leg Press Sled Unilateral", unilateral: true, machine: true, bodyweight: false},
    {name: "Machine Leg Press Unilateral", unilateral: true, machine: true, bodyweight: false},
    {name: "Machine Leg Press Sled", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Bent Arm Shoulder Abductions", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Leg Press", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Lying Leg Curls Unilateral", unilateral: true, machine: true, bodyweight: false},
    {name: "Machine Lying Leg Curls", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Parallel-grip Pulldowns Narrow", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Parallel-grip Pulldowns Wide", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Overhead Press Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Overhead Press", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Pulldowns", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Pullovers", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Reverse Flies", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Seated Leg Curls", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Shoulder Abductions", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Straight Leg Calf Raises", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Triceps Extensions", unilateral: false, machine: true, bodyweight: false},
    {name: "Machine Underhand Pulldowns", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Bent Leg Calf Raises", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Dips Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Dips", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Flat Bench Press Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Flat Bench Press", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Horizontal Rows Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Horizontal Rows", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Incline Bench Press Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Incline Bench Press", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Leg Extensions Unilateral", unilateral: true, machine: true, bodyweight: false},
    {name: "Plate-loaded Leg Extensions", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Leg Press Unilateral", unilateral: true, machine: true, bodyweight: false},
    {name: "Plate-loaded Leg Press", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Overhead Press", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Pulldowns Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Pulldowns", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Straight Leg Calf Raises", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Parallel-grip Pulldowns Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Underhand Pulldowns Alternating", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Parallel-grip Pulldowns", unilateral: false, machine: true, bodyweight: false},
    {name: "Plate-loaded Underhand Pulldowns", unilateral: false, machine: true, bodyweight: false},
  ]
end
