def exercise_bodyparts_list
  return [
    {name: "Barbell Back Squats", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Glutes","Lower Back","Abs"]},
    {name: "Barbell Biceps Curls ~0°", bodyparts: ["Biceps","Forearms"]},
    {name: "Barbell Biceps Curls Preacher/Supported", bodyparts: ["Biceps","Forearms"]},
    {name: "Barbell Clean and Jerks", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Barbell Cleans", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Barbell Dead Lifts", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs"]},
    {name: "Barbell Decline Bench Press - Low", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Barbell Flat Bench Press", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Barbell Front Squats", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs"]},
    {name: "Barbell Hammer Curls", bodyparts: ["Biceps","Forearms"]},
    {name: "Barbell Horizontal Rows", bodyparts: ["Lats","Traps","Rear Delts","Biceps","Forearms"]},
    {name: "Barbell Incline Bench Press - Low", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Barbell Incline Bench Press ~45°", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Barbell Incline Bench Press - High", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Barbell Jerks", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Barbell Narrow Stance Back Squats", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs"]},
    {name: "Barbell Narrow Stance Front Squats", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs"]},
    {name: "Barbell Overhead Press", bodyparts: ["Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Neck Flexors"]},
    {name: "Barbell Preacher/Supported Biceps Curls", bodyparts: ["Biceps","Forearms"]},
    {name: "Barbell Shoulder Shrugs", bodyparts: ["Traps","Neck Flexors"]},
    {name: "Barbell Stiff Legged Dead Lifts", bodyparts: ["Gastrocs","Hamstrings","Adductors","Abductors","Glutes","Lower Back","Abs","Obliques","Lats"]},
    {name: "Barbell Sumo Dead Lifts", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Barbell Triceps Extensions  ~90°", bodyparts: ["Triceps"]},
    {name: "Barbell Walking Lunges", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques"]},
    {name: "Bodyweight Dips", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Bodyweight Dips Plus Weight", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Bodyweight Jump Lunges", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques"]},
    {name: "Bodyweight Squats Unilateral", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques"]},
    {name: "Bodyweight Pull-ups Plus Weight", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Bodyweight Pull-ups", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Bodyweight Push-ups", bodyparts: ["Lower Back","Abs","Front Delts","Triceps","Pecs"]},
    {name: "Bodyweight Squats", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs"]},
    {name: "Bodyweight Chin-ups", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Bodyweight Chin-ups[underhand] Plus Weight", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Bodyweight Triangle Push-ups", bodyparts: ["Lower Back","Abs","Front Delts","Triceps","Pecs"]},
    {name: "Bodyweight Walking Lunges", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques"]},
    {name: "Bodyweight Push-ups Wide", bodyparts: ["Lower Back","Abs","Front Delts","Triceps","Pecs"]},
    {name: "Cable Biceps Curls ~0°", bodyparts: ["Biceps","Forearms"]},
    {name: "Cable Biceps Curls ~45°", bodyparts: ["Biceps","Forearms"]},
    {name: "Cable Biceps Curls ~90°", bodyparts: ["Biceps","Forearms"]},
    {name: "Cable Shoulder Front Raises", bodyparts: ["Front Delts"]},
    {name: "Cable Biceps Hammer Curls", bodyparts: ["Biceps","Forearms"]},
    {name: "Cable Horizontal Rows Unilateral", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Cable Horizontal Rows - Underhanded", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Cable Horizontal Rows - Parallel-grip", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Cable Pulldowns Parallel-grip Narrow", bodyparts: ["Obliques","Lats","Rear Delts","Biceps"]},
    {name: "Cable Pulldowns Parallel-grip Wide", bodyparts: ["Obliques","Lats","Rear Delts","Biceps"]},
    {name: "Cable Pulldowns Underhanded", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Cable Pulldowns", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Cable Tricep Extensions Reverse Grip Unilateral", bodyparts: ["Triceps"]},
    {name: "Cable Tricep Extensions Reverse Grip", bodyparts: ["Triceps"]},
    {name: "Cable Shoulder Raises ~0°", bodyparts: ["Rear Delts","Delts"]},
    {name: "Cable Shoulder Raises ~45°", bodyparts: ["Rear Delts","Delts"]},
    {name: "Cable Triceps Extensions  ~0°", bodyparts: ["Triceps"]},
    {name: "Cable Triceps Extensions  ~90°", bodyparts: ["Triceps"]},
    {name: "Crossover Reverse Flies", bodyparts: ["Triceps"]},
    {name: "Crossover Shoulder Raises ~0°", bodyparts: ["Rear Delts","Delts"]},
    {name: "Crossover Shoulder Raises ~45°", bodyparts: ["Rear Delts","Delts"]},
    {name: "Crossover 'Y' Pulldowns", bodyparts: ["Lats","Traps","Biceps"]},
    {name: "Crossover Butterflies", bodyparts: ["Biceps","Pecs"]},
    {name: "Crossover Butterflies Incline", bodyparts: ["Biceps","Pecs"]},
    {name: "Crossover Decline Bench Press", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Crossover Flat Bench Press", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Crossover Incline Bench Press", bodyparts: ["Front Delts","Triceps","Forearms","Pecs"]},
    {name: "Dumbbell Biceps Curls", bodyparts: ["Biceps","Forearms"]},
    {name: "Dumbbell Biceps Curls Reclined", bodyparts: ["Biceps","Forearms"]},
    {name: "Dumbbell Butterflies", bodyparts: ["Pecs"]},
    {name: "Dumbbell Dead Lifts", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Neck Flexors"]},
    {name: "Dumbbell Decline Bench Press - Low", bodyparts: ["Triceps","Pecs"]},
    {name: "Dumbbell Flat Bench Press", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Dumbbell Front Raises", bodyparts: ["Delts","Front Delts"]},
    {name: "Dumbbell Front Squats", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques"]},
    {name: "Dumbbell Hammer Biceps Curls", bodyparts: ["Biceps","Forearms"]},
    {name: "Dumbbell Horizontal Rows", bodyparts: ["Obliques","Lats","Traps","Rear Delts","Biceps"]},
    {name: "Dumbbell Incline Bench Press - Low", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Dumbbell Incline Bench Press ~45°", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Dumbbell Incline Bench Press - High", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Dumbbell Jump Lunges", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Dumbbell Shoulder Press", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Dumbbell Preacher/Supported Biceps Curls", bodyparts: ["Biceps","Forearms"]},
    {name: "Dumbbell Shoulder Raises", bodyparts: ["Rear Delts","Delts","Front Delts"]},
    {name: "Dumbbell Shoulder Shrugs", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Dumbbell Squats", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Dumbbell Stiff Legged Dead Lifts", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Lying Triceps Extensions", bodyparts: ["Triceps"]},
    {name: "Dumbbell Walking Lunges", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Machine Bent Leg Calf Raises", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Machine Bicep Curls Unsupported Alternating", bodyparts: ["Biceps","Forearms"]},
    {name: "Machine Bicep Curls Supported Alternating", bodyparts: ["Biceps","Forearms"]},
    {name: "Machine Bicep Curls Reclined Alternating", bodyparts: ["Biceps","Forearms"]},
    {name: "Machine Biceps Curls Unsupported", bodyparts: ["Biceps","Forearms"]},
    {name: "Machine Biceps Curls Supported", bodyparts: ["Biceps","Forearms"]},
    {name: "Machine Biceps Curls Reclined", bodyparts: ["Biceps","Forearms"]},
    {name: "Machine Flies", bodyparts: ["Pecs"]},
    {name: "Machine Dips", bodyparts: ["Front Delts","Triceps"]},
    {name: "Machine Flat Bench Press Alternating", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Machine Flat Bench Press", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Machine Glute Kick-backs Unilateral", bodyparts: ["Hamstrings","Glutes","Lower Back"]},
    {name: "Machine Horizontal Rows Alternating", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Machine Horizontal Rows", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Machine Incline Bench Press Alternating", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Machine Incline Bench Press", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Machine Leg Abductions", bodyparts: ["Abductors","Hip Flexors","Glutes"]},
    {name: "Machine Leg Adductions", bodyparts: ["Adductors"]},
    {name: "Machine Leg Extensions Unilateral", bodyparts: ["Quads"]},
    {name: "Machine Leg Extensions", bodyparts: ["Quads"]},
    {name: "Machine Leg Press Sled Unilateral", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes"]},
    {name: "Machine Leg Press Unilateral", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes"]},
    {name: "Machine Leg Press Sled", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes"]},
    {name: "Machine Bent Arm Shoulder Abductions", bodyparts: ["Rear Delts","Delts","Front Delts"]},
    {name: "Machine Leg Press", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes"]},
    {name: "Machine Lying Leg Curls Unilateral", bodyparts: ["Hamstrings"]},
    {name: "Machine Lying Leg Curls", bodyparts: ["Hamstrings"]},
    {name: "Machine Parallel-grip Pulldowns Narrow", bodyparts: ["Lats"]},
    {name: "Machine Parallel-grip Pulldowns Wide", bodyparts: ["Lats"]},
    {name: "Machine Overhead Press Alternating", bodyparts: ["Rear Delts","Delts","Front Delts","Triceps"]},
    {name: "Machine Overhead Press", bodyparts: ["Rear Delts","Delts","Front Delts","Triceps"]},
    {name: "Machine Pulldowns", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Machine Pullovers", bodyparts: ["Abs","Obliques","Lats","Front Delts","Rotator Cuff","Triceps","Pecs"]},
    {name: "Machine Reverse Flies", bodyparts: ["Rear Delts"]},
    {name: "Machine Seated Leg Curls", bodyparts: ["Hamstrings"]},
    {name: "Machine Shoulder Abductions", bodyparts: ["Rear Delts","Delts","Front Delts"]},
    {name: "Machine Straight Leg Calf Raises", bodyparts: ["Gastrocs"]},
    {name: "Machine Triceps Extensions", bodyparts: ["Triceps"]},
    {name: "Machine Underhand Pulldowns", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Plate-loaded Bent Leg Calf Raises", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Plate-loaded Dips Alternating", bodyparts: ["Front Delts","Triceps"]},
    {name: "Plate-loaded Dips", bodyparts: ["Front Delts","Triceps"]},
    {name: "Plate-loaded Flat Bench Press Alternating", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Plate-loaded Flat Bench Press", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Plate-loaded Horizontal Rows Alternating", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Plate-loaded Horizontal Rows", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Plate-loaded Incline Bench Press Alternating", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Plate-loaded Incline Bench Press", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Plate-loaded Leg Extensions Unilateral", bodyparts: ["Quads"]},
    {name: "Plate-loaded Leg Extensions", bodyparts: ["Quads"]},
    {name: "Plate-loaded Leg Press Unilateral", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes"]},
    {name: "Plate-loaded Leg Press", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes"]},
    {name: "Plate-loaded Overhead Press", bodyparts: ["Rear Delts","Delts","Front Delts","Triceps"]},
    {name: "Plate-loaded Pulldowns Alternating", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Plate-loaded Pulldowns", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Plate-loaded Straight Leg Calf Raises", bodyparts: ["Gastrocs"]},
    {name: "Plate-loaded Parallel-grip Pulldowns Alternating", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Plate-loaded Underhand Pulldowns Alternating", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Plate-loaded Parallel-grip Pulldowns", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Plate-loaded Underhand Pulldowns", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]}
  ]
end
