def exercise_bodyparts_list
  return [
    {name: "Bench Press: Decline Low - Barbell", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Bench Press: Decline Low - Dumbbell", bodyparts: ["Triceps","Pecs"]},
    {name: "Bench Press: Flat - Barbell", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Bench Press: Flat - Crossover", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Bench Press: Flat - Dumbbell", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Bench Press: Incline High - Barbell", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Bench Press: Incline High - Dumbbell", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Bench Press: Incline Low - Barbell", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Bench Press: Incline Low - Dumbbell", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Bench Press: Incline Middle - Barbell", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Bench Press: Incline Middle - Dumbbell", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Bent Leg Calf Raises - Machine", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Bent Leg Calf Raises - Plate-loaded", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Bicep Curls - Dumbbell", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Curls - Barbell", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Curls - Cable", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Curls ~45° - Cable", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Curls ~90° - Cable", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Curls Preacher/Supported - Barbell", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Curls Reclined - Dumbbell", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Curls Reclined - Machine", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Curls Reclined Alternating - Machine", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Curls Supported - Machine", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Curls Supported Alternating - Machine", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Curls Unsupported - Machine", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Curls Unsupported Alternating - Machine", bodyparts: ["Biceps","Forearms"]},
    {name: "Bicep Hammer Curls - Cable", bodyparts: ["Biceps","Forearms"]},
    {name: "Butterflies - Crossover", bodyparts: ["Biceps","Pecs"]},
    {name: "Butterflies - Dumbbell", bodyparts: ["Pecs"]},
    {name: "Butterflies - Machine", bodyparts: ["Pecs"]},
    {name: "Butterflies Incline - Crossover", bodyparts: ["Biceps","Pecs"]},
    {name: "Chest Press: Decline - Crossover", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Chest Press: Flat - Machine", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Chest Press: Flat - Plate-loaded", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Chest Press: Flat Alternating - Machine", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Chest Press: Flat Alternating - Plate-loaded", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Chest Press: Incline - Crossover", bodyparts: ["Front Delts","Triceps","Forearms","Pecs"]},
    {name: "Chest Press: Incline - Machine", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Chest Press: Incline - Plate-loaded", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Chest Press: Incline Alternating - Machine", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Chest Press: Incline Alternating - Plate-loaded", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Chin-ups - Bodyweight", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Chin-ups Plus Weight - Bodyweight", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Clean and Jerks - Barbell", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Cleans - Barbell", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Dead Lifts - Barbell", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs"]},
    {name: "Dead Lifts - Dumbbell", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Neck Flexors"]},
    {name: "Dips - Bodyweight", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Dips - Machine", bodyparts: ["Front Delts","Triceps"]},
    {name: "Dips - Plate-loaded", bodyparts: ["Front Delts","Triceps"]},
    {name: "Dips Alternating - Plate-loaded", bodyparts: ["Front Delts","Triceps"]},
    {name: "Dips Plus Weight - Bodyweight", bodyparts: ["Front Delts","Triceps","Pecs"]},
    {name: "Flies - Machine", bodyparts: ["Pecs"]},
    {name: "Front Raises - Dumbbell", bodyparts: ["Delts","Front Delts"]},
    {name: "Front Squats - Barbell", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs"]},
    {name: "Front Squats - Dumbbell", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques"]},
    {name: "Glute Kick-backs Unilateral - Machine", bodyparts: ["Hamstrings","Glutes","Lower Back"]},
    {name: "Hammer Bicep Curls - Dumbbell", bodyparts: ["Biceps","Forearms"]},
    {name: "Hammer Curls - Barbell", bodyparts: ["Biceps","Forearms"]},
    {name: "Horizontal Rows - Barbell", bodyparts: ["Lats","Traps","Rear Delts","Biceps","Forearms"]},
    {name: "Horizontal Rows - Dumbbell", bodyparts: ["Obliques","Lats","Traps","Rear Delts","Biceps"]},
    {name: "Horizontal Rows - Machine", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Horizontal Rows - Plate-loaded", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Horizontal Rows Alternating - Machine", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Horizontal Rows Alternating - Plate-loaded", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Horizontal Rows Unilateral - Cable", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Horizontal Rows: Parallel-grip - Cable", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Horizontal Rows: Underhanded - Cable", bodyparts: ["Lats","Traps","Rear Delts","Biceps"]},
    {name: "Jerks - Barbell", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Jump Lunges - Bodyweight", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques"]},
    {name: "Jump Lunges - Dumbbell", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Lat Pulldowns - Crossover", bodyparts: ["Lats","Traps","Biceps"]},
    {name: "Leg Abductions - Machine", bodyparts: ["Abductors","Hip Flexors","Glutes"]},
    {name: "Leg Adductions - Machine", bodyparts: ["Adductors"]},
    {name: "Leg Extensions - Machine", bodyparts: ["Quads"]},
    {name: "Leg Extensions - Plate-loaded", bodyparts: ["Quads"]},
    {name: "Leg Extensions Unilateral - Machine", bodyparts: ["Quads"]},
    {name: "Leg Extensions Unilateral - Plate-loaded", bodyparts: ["Quads"]},
    {name: "Leg Press - Machine", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes"]},
    {name: "Leg Press - Plate-loaded", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes"]},
    {name: "Leg Press Sled - Machine", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes"]},
    {name: "Leg Press Sled Unilateral - Machine", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes"]},
    {name: "Leg Press Unilateral - Machine", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes"]},
    {name: "Leg Press Unilateral - Plate-loaded", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes"]},
    {name: "Lying Leg Curls - Machine", bodyparts: ["Hamstrings"]},
    {name: "Lying Leg Curls Unilateral - Machine", bodyparts: ["Hamstrings"]},
    {name: "Narrow Stance Back Squats - Barbell", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs"]},
    {name: "Narrow Stance Front Squats - Barbell", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs"]},
    {name: "Overhead Press - Barbell", bodyparts: ["Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Neck Flexors"]},
    {name: "Overhead Press - Machine", bodyparts: ["Rear Delts","Delts","Front Delts","Triceps"]},
    {name: "Overhead Press - Plate-loaded", bodyparts: ["Rear Delts","Delts","Front Delts","Triceps"]},
    {name: "Overhead Press Alternating - Machine", bodyparts: ["Rear Delts","Delts","Front Delts","Triceps"]},
    {name: "Parallel-grip Pulldowns - Plate-loaded", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Parallel-grip Pulldowns Alternating - Plate-loaded", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Parallel-grip Pulldowns Narrow - Machine", bodyparts: ["Lats"]},
    {name: "Parallel-grip Pulldowns Wide - Machine", bodyparts: ["Lats"]},
    {name: "Preacher/Supported Bicep Curls - Barbell", bodyparts: ["Biceps","Forearms"]},
    {name: "Preacher/Supported Bicep Curls - Dumbbell", bodyparts: ["Biceps","Forearms"]},
    {name: "Pull-ups - Bodyweight", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Pull-ups Plus Weight - Bodyweight", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Pulldowns - Cable", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Pulldowns - Machine", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Pulldowns - Plate-loaded", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Pulldowns Alternating - Plate-loaded", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Pulldowns Parallel-grip Narrow - Cable", bodyparts: ["Obliques","Lats","Rear Delts","Biceps"]},
    {name: "Pulldowns Parallel-grip Wide - Cable", bodyparts: ["Obliques","Lats","Rear Delts","Biceps"]},
    {name: "Pulldowns Underhanded - Cable", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Pullovers - Machine", bodyparts: ["Abs","Obliques","Lats","Front Delts","Rotator Cuff","Triceps","Pecs"]},
    {name: "Push-ups - Bodyweight", bodyparts: ["Lower Back","Abs","Front Delts","Triceps","Pecs"]},
    {name: "Push-ups Wide - Bodyweight", bodyparts: ["Lower Back","Abs","Front Delts","Triceps","Pecs"]},
    {name: "Reverse Flies - Crossover", bodyparts: ["Triceps"]},
    {name: "Reverse Flies - Machine", bodyparts: ["Rear Delts"]},
    {name: "Rotators: Anterior Rotation Sagital - Cable", bodyparts: ["Rear Delts","Delts","Front Delts","Rotator Cuff"]},
    {name: "Rotators: Anterior Rotation Tranverse - Cable", bodyparts: ["Rear Delts","Delts","Front Delts","Rotator Cuff"]},
    {name: "Rotators: Posterior Rotation Sagital - Cable", bodyparts: ["Rear Delts","Delts","Front Delts","Rotator Cuff"]},
    {name: "Rotators: Posterior Rotation Tranverse - Cable", bodyparts: ["Rear Delts","Delts","Front Delts","Rotator Cuff"]},
    {name: "Seated Leg Curls - Machine", bodyparts: ["Hamstrings"]},
    {name: "Shoulder Abductions - Machine", bodyparts: ["Rear Delts","Delts","Front Delts"]},
    {name: "Shoulder Front Raises - Cable", bodyparts: ["Front Delts"]},
    {name: "Shoulder Press - Dumbbell", bodyparts: ["Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Neck Flexors"]},
    {name: "Shoulder Press - Machine", bodyparts: ["Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Neck Flexors"]},
    {name: "Shoulder Press - Plate-loaded", bodyparts: ["Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Neck Flexors"]},
    {name: "Shoulder Raises - Dumbbell", bodyparts: ["Rear Delts","Delts","Front Delts"]},
    {name: "Shoulder Raises - Cable", bodyparts: ["Rear Delts","Delts"]},
    {name: "Shoulder Raises - Crossover", bodyparts: ["Rear Delts","Delts"]},
    {name: "Shoulder Raises ~45° - Cable", bodyparts: ["Rear Delts","Delts"]},
    {name: "Shoulder Raises ~45° - Crossover", bodyparts: ["Rear Delts","Delts"]},
    {name: "Shoulder Shrugs - Barbell", bodyparts: ["Traps","Neck Flexors"]},
    {name: "Shoulder Shrugs - Dumbbell", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Squats - Barbell", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Glutes","Lower Back","Abs"]},
    {name: "Squats - Bodyweight", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs"]},
    {name: "Squats - Dumbbell", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Squats Unilateral - Bodyweight", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques"]},
    {name: "Stiff Legged Dead Lifts - Barbell", bodyparts: ["Gastrocs","Hamstrings","Adductors","Abductors","Glutes","Lower Back","Abs","Obliques","Lats"]},
    {name: "Stiff Legged Dead Lifts - Dumbbell", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Straight Leg Calf Raises - Machine", bodyparts: ["Gastrocs"]},
    {name: "Straight Leg Calf Raises - Plate-loaded", bodyparts: ["Gastrocs"]},
    {name: "Sumo Dead Lifts - Barbell", bodyparts: ["Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
    {name: "Triangle Push-ups - Bodyweight", bodyparts: ["Lower Back","Abs","Front Delts","Triceps","Pecs"]},
    {name: "Tricep Extensions - Cable", bodyparts: ["Triceps"]},
    {name: "Tricep Extensions - Lying Barbell", bodyparts: ["Triceps"]},
    {name: "Tricep Extensions - Lying Dumbbell", bodyparts: ["Triceps"]},
    {name: "Tricep Extensions - Machine", bodyparts: ["Triceps"]},
    {name: "Tricep Extensions - Overhead Barbell", bodyparts: ["Triceps"]},
    {name: "Tricep Extensions - Overhead Cable", bodyparts: ["Triceps"]},
    {name: "Tricep Extensions Reverse Grip - Cable", bodyparts: ["Triceps"]},
    {name: "Tricep Extensions Reverse Grip Unilateral - Cable", bodyparts: ["Triceps"]},
    {name: "Underhand Pulldowns - Machine", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Underhand Pulldowns - Plate-loaded", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Underhand Pulldowns Alternating - Plate-loaded", bodyparts: ["Obliques","Lats","Rear Delts","Biceps","Forearms"]},
    {name: "Walking Lunges - Barbell", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques"]},
    {name: "Walking Lunges - Bodyweight", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques"]},
    {name: "Walking Lunges - Dumbbell", bodyparts: ["Gastrocs","Soleus","Quads","Hamstrings","Adductors","Abductors","Hip Flexors","Glutes","Lower Back","Abs","Obliques","Lats","Traps","Rear Delts","Delts","Front Delts","Rotator Cuff","Triceps","Biceps","Forearms","Pecs","Neck Flexors"]},
  ]
end
