def exercise_list
  return [
    {name: "Bench Press: Decline Low - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Bench Press: Decline Low - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Bench Press: Flat - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Bench Press: Flat - Crossover", unilateral: true, machine: false, bodyweight: false},
    {name: "Bench Press: Flat - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Bench Press: Incline High - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Bench Press: Incline High - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Bench Press: Incline Low - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Bench Press: Incline Low - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Bench Press: Incline Middle - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Bench Press: Incline Middle - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Bent Leg Calf Raises - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Bent Leg Calf Raises - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Bicep Curls - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Bicep Curls - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Bicep Curls - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Bicep Curls ~45° - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Bicep Curls ~90° - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Bicep Curls Preacher/Supported - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Bicep Curls Reclined - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Bicep Curls Reclined - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Bicep Curls Reclined Alternating - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Bicep Curls Supported - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Bicep Curls Supported Alternating - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Bicep Curls Unsupported - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Bicep Curls Unsupported Alternating - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Bicep Hammer Curls - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Butterflies - Crossover", unilateral: true, machine: false, bodyweight: false},
    {name: "Butterflies - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Butterflies - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Butterflies Incline - Crossover", unilateral: true, machine: false, bodyweight: false},
    {name: "Chest Press: Decline - Crossover", unilateral: true, machine: false, bodyweight: false},
    {name: "Chest Press: Flat - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Chest Press: Flat - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Chest Press: Flat Alternating - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Chest Press: Flat Alternating - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Chest Press: Incline - Crossover", unilateral: true, machine: false, bodyweight: false},
    {name: "Chest Press: Incline - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Chest Press: Incline - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Chest Press: Incline Alternating - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Chest Press: Incline Alternating - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Chin-ups - Bodyweight", unilateral: false, machine: false, bodyweight: true},
    {name: "Chin-ups Plus Weight - Bodyweight", unilateral: false, machine: false, bodyweight: true},
    {name: "Clean and Jerks - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Cleans - Barbell", unilateral: false, machine: false, bodyweight: true},
    {name: "Dead Lifts - Barbell", unilateral: false, machine: false, bodyweight: true},
    {name: "Dead Lifts - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Dips - Bodyweight", unilateral: false, machine: false, bodyweight: true},
    {name: "Dips - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Dips - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Dips Alternating - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Dips Plus Weight - Bodyweight", unilateral: false, machine: false, bodyweight: true},
    {name: "Flies - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Front Raises - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Front Squats - Barbell", unilateral: false, machine: false, bodyweight: true},
    {name: "Front Squats - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Glute Kick-backs Unilateral - Machine", unilateral: true, machine: true, bodyweight: false},
    {name: "Hammer Bicep Curls - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Hammer Curls - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Horizontal Rows - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Horizontal Rows - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Horizontal Rows - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Horizontal Rows - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Horizontal Rows Alternating - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Horizontal Rows Alternating - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Horizontal Rows Unilateral - Cable", unilateral: true, machine: false, bodyweight: false},
    {name: "Horizontal Rows: Parallel-grip - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Horizontal Rows: Underhanded - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Jerks - Barbell", unilateral: false, machine: false, bodyweight: true},
    {name: "Jump Lunges - Bodyweight", unilateral: false, machine: false, bodyweight: true},
    {name: "Jump Lunges - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Lat Pulldowns - Crossover", unilateral: true, machine: false, bodyweight: false},
    {name: "Leg Abductions - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Leg Adductions - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Leg Extensions - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Leg Extensions - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Leg Extensions Unilateral - Machine", unilateral: true, machine: true, bodyweight: false},
    {name: "Leg Extensions Unilateral - Plate-loaded", unilateral: true, machine: true, bodyweight: false},
    {name: "Leg Press - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Leg Press - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Leg Press Sled - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Leg Press Sled Unilateral - Machine", unilateral: true, machine: true, bodyweight: false},
    {name: "Leg Press Unilateral - Machine", unilateral: true, machine: true, bodyweight: false},
    {name: "Leg Press Unilateral - Plate-loaded", unilateral: true, machine: true, bodyweight: false},
    {name: "Lying Leg Curls - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Lying Leg Curls Unilateral - Machine", unilateral: true, machine: true, bodyweight: false},
    {name: "Narrow Stance Back Squats - Barbell", unilateral: false, machine: false, bodyweight: true},
    {name: "Narrow Stance Front Squats - Barbell", unilateral: false, machine: false, bodyweight: true},
    {name: "Overhead Press - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Overhead Press - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Overhead Press - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Overhead Press Alternating - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Parallel-grip Pulldowns - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Parallel-grip Pulldowns Alternating - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Parallel-grip Pulldowns Narrow - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Parallel-grip Pulldowns Wide - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Preacher/Supported Bicep Curls - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Preacher/Supported Bicep Curls - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Pull-ups - Bodyweight", unilateral: false, machine: false, bodyweight: true},
    {name: "Pull-ups Plus Weight - Bodyweight", unilateral: false, machine: false, bodyweight: true},
    {name: "Pulldowns - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Pulldowns - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Pulldowns - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Pulldowns Alternating - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Pulldowns Parallel-grip Narrow - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Pulldowns Parallel-grip Wide - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Pulldowns Underhanded - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Pullovers - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Push-ups - Bodyweight", unilateral: false, machine: false, bodyweight: true},
    {name: "Push-ups Wide - Bodyweight", unilateral: false, machine: false, bodyweight: true},
    {name: "Reverse Flies - Crossover", unilateral: true, machine: false, bodyweight: false},
    {name: "Reverse Flies - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Rotators: Anterior Rotation Sagital - Cable", unilateral: true, machine: false, bodyweight: false},
    {name: "Rotators: Anterior Rotation Tranverse - Cable", unilateral: true, machine: false, bodyweight: false},
    {name: "Rotators: Posterior Rotation Sagital - Cable", unilateral: true, machine: false, bodyweight: false},
    {name: "Rotators: Posterior Rotation Tranverse - Cable", unilateral: true, machine: false, bodyweight: false},
    {name: "Seated Leg Curls - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Shoulder Abductions - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Shoulder Front Raises - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Shoulder Press - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Shoulder Press - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Shoulder Press - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Shoulder Raises - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Shoulder Raises - Cable", unilateral: true, machine: false, bodyweight: false},
    {name: "Shoulder Raises - Crossover", unilateral: true, machine: false, bodyweight: false},
    {name: "Shoulder Raises ~45° - Cable", unilateral: true, machine: false, bodyweight: false},
    {name: "Shoulder Raises ~45° - Crossover", unilateral: true, machine: false, bodyweight: false},
    {name: "Shoulder Shrugs - Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Shoulder Shrugs - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Squats - Barbell", unilateral: false, machine: false, bodyweight: true},
    {name: "Squats - Bodyweight", unilateral: false, machine: false, bodyweight: true},
    {name: "Squats - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Squats Unilateral - Bodyweight", unilateral: true, machine: false, bodyweight: true},
    {name: "Stiff Legged Dead Lifts - Barbell", unilateral: false, machine: false, bodyweight: true},
    {name: "Stiff Legged Dead Lifts - Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Straight Leg Calf Raises - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Straight Leg Calf Raises - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Sumo Dead Lifts - Barbell", unilateral: false, machine: false, bodyweight: true},
    {name: "Triangle Push-ups - Bodyweight", unilateral: false, machine: false, bodyweight: true},
    {name: "Tricep Extensions - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Tricep Extensions - Lying Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Tricep Extensions - Lying Dumbbell", unilateral: true, machine: false, bodyweight: false},
    {name: "Tricep Extensions - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Tricep Extensions - Overhead Barbell", unilateral: false, machine: false, bodyweight: false},
    {name: "Tricep Extensions - Overhead Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Tricep Extensions Reverse Grip - Cable", unilateral: false, machine: false, bodyweight: false},
    {name: "Tricep Extensions Reverse Grip Unilateral - Cable", unilateral: true, machine: false, bodyweight: false},
    {name: "Underhand Pulldowns - Machine", unilateral: false, machine: true, bodyweight: false},
    {name: "Underhand Pulldowns - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Underhand Pulldowns Alternating - Plate-loaded", unilateral: false, machine: true, bodyweight: false},
    {name: "Walking Lunges - Barbell", unilateral: false, machine: false, bodyweight: true},
    {name: "Walking Lunges - Bodyweight", unilateral: false, machine: false, bodyweight: true},
    {name: "Walking Lunges - Dumbbell", unilateral: true, machine: false, bodyweight: false},
  ]
end
