def new_exercise_bodyparts_list
  return [
    {name: "Bench Press: Decline", bodyparts: ["Front Delts", "Triceps", "Pecs"]},
    {name: "Bench Press: Flat", bodyparts: ["Front Delts", "Triceps", "Pecs"]},
    {name: "Bench Press: Incline", bodyparts: ["Delts", "Front Delts", "Triceps", "Pecs"]},
    {name: "Bicep Curls: Hammer Grip", bodyparts: ["Biceps", "Forearms"]},
    {name: "Bicep Curls: Overhand Grip", bodyparts: ["Biceps", "Forearms"]},
    {name: "Bicep Curls: Preacher/Supported", bodyparts: ["Biceps", "Forearms"]},
    {name: "Bicep Curls: Reclined", bodyparts: ["Biceps", "Forearms"]},
    {name: "Bicep Curls", bodyparts: ["Biceps", "Forearms"]},
    {name: "Calf Raises: Bent Leg", bodyparts: ["Soleus"]},
    {name: "Calf Raises: Straight Leg", bodyparts: ["Gastrocs"]},
    {name: "Chest Flies: Incline", bodyparts: ["Delts", "Front Delts", "Pecs"]},
    {name: "Chest Flies", bodyparts: ["Front Delts", "Pecs"]},
    {name: "Chin-ups", bodyparts: ["Lats", "Biceps"]},
    {name: "Clean & Jerks", bodyparts: ["Gastrocs", "Soleus", "Quads", "Hamstrings", "Adductors", "Abductors", "Hip Flexors", "Glutes", "Lower Back", "Abs", "Obliques", "Traps", "Rear Delts", "Delts", "Front Delts", "Triceps", "Biceps", "Pecs", "Neck Flexors"]},
    {name: "Cleans", bodyparts: ["Gastrocs", "Soleus", "Quads", "Hamstrings", "Adductors", "Abductors", "Hip Flexors", "Glutes", "Lower Back", "Abs", "Obliques", "Traps", "Rear Delts", "Delts", "Front Delts", "Triceps", "Biceps", "Pecs", "Neck Flexors"]},
    {name: "Dead Lifts: Stiff Legged", bodyparts: ["Quads", "Hamstrings", "Adductors", "Abductors", "Hip Flexors", "Glutes", "Lower Back", "Forearms"]},
    {name: "Dead Lifts: Sumo", bodyparts: ["Quads", "Hamstrings", "Adductors", "Abductors", "Hip Flexors", "Glutes", "Lower Back", "Forearms"]},
    {name: "Dead Lifts", bodyparts: ["Quads", "Hamstrings", "Adductors", "Abductors", "Hip Flexors", "Glutes", "Lower Back", "Forearms"]},
    {name: "Dips: Bench / Feet on Floor", bodyparts: ["Lats", "Front Delts", "Rotator Cuff", "Triceps", "Pecs"]},
    {name: "Dips: Bench / Feet on Floor", bodyparts: ["Lats", "Front Delts", "Rotator Cuff", "Triceps", "Pecs"]},
    {name: "Dips: Bench / Feet on Bench", bodyparts: ["Lats", "Front Delts", "Rotator Cuff", "Triceps", "Pecs"]},
    {name: "Dips", bodyparts: ["Lats", "Front Delts", "Rotator Cuff", "Triceps", "Pecs"]},
    {name: "Glute Kick-backs", bodyparts: ["Hamstrings", "Glutes", "Lower Back"]},
    {name: "Horizontal Rows: One Arm", bodyparts: ["Lower Back", "Obliques", "Lats", "Traps", "Rear Delts", "Biceps", "Forearms"]},
    {name: "Horizontal Rows: Underhand Grip", bodyparts: ["Lower Back", "Lats", "Traps", "Rear Delts", "Biceps", "Forearms"]},
    {name: "Horizontal Rows", bodyparts: ["Lower Back", "Lats", "Traps", "Rear Delts", "Biceps", "Forearms"]},
    {name: "Jerks", bodyparts: ["Traps", "Rear Delts", "Delts", "Front Delts", "Triceps", "Neck Flexors"]},
    {name: "Jump Lunges", bodyparts: ["Gastrocs", "Soleus", "Quads", "Hamstrings", "Adductors", "Abductors", "Hip Flexors", "Glutes", "Lower Back", "Abs", "Obliques"]},
    {name: "Lat Pulldowns: Parallel Grip-Narrow", bodyparts: ["Lats", "Biceps", "Forearms"]},
    {name: "Lat Pulldowns: Parallel Grip", bodyparts: ["Lats", "Biceps", "Forearms"]},
    {name: "Lat Pulldowns: Underhand Grip", bodyparts: ["Lats", "Biceps", "Forearms"]},
    {name: "Lat Pulldowns", bodyparts: ["Lats", "Biceps", "Forearms"]},
    {name: "Leg Abductions", bodyparts: ["Abductors", "Glutes"]},
    {name: "Leg Adductions", bodyparts: ["Adductors"]},
    {name: "Leg Curls: Lying One Leg", bodyparts: ["Hamstrings"]},
    {name: "Leg Curls: Lying", bodyparts: ["Hamstrings"]},
    {name: "Leg Curls: Seated One Leg", bodyparts: ["Hamstrings"]},
    {name: "Leg Curls: Seated", bodyparts: ["Hamstrings"]},
    {name: "Leg Extensions: One Leg", bodyparts: ["Quads", "Hip Flexors"]},
    {name: "Leg Extensions", bodyparts: ["Quads", "Hip Flexors"]},
    {name: "Leg Press: One Leg", bodyparts: ["Quads", "Hamstrings", "Adductors", "Abductors", "Hip Flexors", "Glutes", "Lower Back"]},
    {name: "Leg Press", bodyparts: ["Quads", "Hamstrings", "Adductors", "Abductors", "Hip Flexors", "Glutes", "Lower Back"]},
    {name: "Pull-ups", bodyparts: ["Lats", "Biceps", "Forearms"]},
    {name: "Pullovers", bodyparts: ["Abs", "Obliques", "Lats", "Rotator Cuff", "Triceps", "Pecs"]},
    {name: "Push-ups: Triangle Base", bodyparts: ["Abs", "Obliques", "Front Delts", "Triceps", "Pecs"]},
    {name: "Push-ups: Wide Base", bodyparts: ["Abs", "Obliques", "Front Delts", "Triceps", "Pecs"]},
    {name: "Push-ups", bodyparts: ["Abs", "Obliques", "Front Delts", "Triceps", "Pecs"]},
    {name: "Reverse Flies", bodyparts: ["Traps", "Rear Delts", "Rotator Cuff", "Triceps"]},
    {name: "Rotators: Anterior Rotation Sagital", bodyparts: ["Rotator Cuff"]},
    {name: "Rotators: Anterior Rotation Tranverse", bodyparts: ["Rotator Cuff"]},
    {name: "Rotators: Posterior Rotation Sagital", bodyparts: ["Rotator Cuff"]},
    {name: "Rotators: Posterior Rotation Tranverse", bodyparts: ["Rotator Cuff"]},
    {name: "Shoulder Press", bodyparts: ["Traps", "Rear Delts", "Delts", "Front Delts", "Rotator Cuff", "Triceps", "Neck Flexors"]},
    {name: "Shoulder Raises: Front", bodyparts: ["Delts", "Front Delts", "Rotator Cuff", "Triceps", "Neck Flexors"]},
    {name: "Shoulder Raises: Lateral", bodyparts: ["Rear Delts", "Delts", "Front Delts", "Rotator Cuff", "Triceps", "Neck Flexors"]},
    {name: "Shoulder Shrugs", bodyparts: ["Traps", "Triceps", "Neck Flexors"]},
    {name: "Squats: Back Narrow Stance", bodyparts: ["Quads", "Hamstrings", "Adductors", "Abductors", "Hip Flexors", "Glutes", "Lower Back", "Neck Flexors"]},
    {name: "Squats: Back", bodyparts: ["Quads", "Hamstrings", "Adductors", "Abductors", "Hip Flexors", "Glutes", "Lower Back", "Neck Flexors"]},
    {name: "Squats: Front", bodyparts: ["Quads", "Hamstrings", "Adductors", "Abductors", "Hip Flexors", "Glutes", "Lower Back", "Neck Flexors"]},
    {name: "Tricep Extensions: Lying", bodyparts: ["Triceps"]},
    {name: "Tricep Extensions: Overhead", bodyparts: ["Triceps"]},
    {name: "Tricep Extensions: Reverse Grip", bodyparts: ["Triceps"]},
    {name: "Tricep Extensions", bodyparts: ["Triceps"]},
    {name: "Tricep Extensions: One Arm", bodyparts: ["Triceps"]},
    {name: "Walking Lunges", bodyparts: ["Gastrocs", "Quads", "Hamstrings", "Adductors", "Abductors", "Hip Flexors", "Glutes", "Lower Back", "Abs", "Obliques"]},
  ]
end
