def new_exercises
	return [
		{name: "Bench Press: Decline",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Bench Press: Flat",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Bench Press: Incline",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Bicep Curls: Hammer Grip",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Bicep Curls: Overhand Grip",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Bicep Curls: Preacher/Supported",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Bicep Curls: Reclined",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Bicep Curls",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Calf Raises: Bent Leg",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Calf Raises: Straight Leg",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Chest Flies: Incline",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Chest Flies",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Chin-ups",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Clean & Jerks",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Cleans",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Dead Lifts: Stiff Legged",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Dead Lifts: Sumo",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Dead Lifts",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Dips: Bench / Feet on Floor",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Dips: Bench / Feet on Bench",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Dips",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Glute Kick-backs",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Horizontal Rows: One Arm",  unilateral: true, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Horizontal Rows: Underhand Grip",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Horizontal Rows",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Jerks",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Jump Lunges",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Lat Pulldowns: Parallel Grip-Narrow",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Lat Pulldowns: Parallel Grip",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Lat Pulldowns: Underhand Grip",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Lat Pulldowns",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Leg Abductions",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Leg Adductions",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Leg Curls: Lying One Leg",  unilateral: true, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Leg Curls: Lying",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Leg Curls: Seated One Leg",  unilateral: true, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Leg Curls: Seated",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Leg Extensions: One Leg",  unilateral: true, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Leg Extensions",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Leg Press: One Leg",  unilateral: true, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Leg Press",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Pull-ups",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Pullovers",  unilateral: false, force_bilateral: true, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Push-ups: Triangle Base",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: 1.376, f_mech_ad_override: 1.420, bodyweight: false},
		{name: "Push-ups: Wide Base",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: 1.376, f_mech_ad_override: 1.420, bodyweight: false},
		{name: "Push-ups",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: 1.376, f_mech_ad_override: 1.420, bodyweight: false},
		{name: "Reverse Flies",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Rotators: Anterior Rotation Sagital",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Rotators: Anterior Rotation Tranverse",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Rotators: Posterior Rotation Sagital",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Rotators: Posterior Rotation Tranverse",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Shoulder Press",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Shoulder Raises: Front",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Shoulder Raises: Lateral",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Shoulder Shrugs",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Squats: Back Narrow Stance",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Squats: Back",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Squats: Front",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Tricep Extensions: Lying",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Tricep Extensions: Overhead",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Tricep Extensions: Reverse Grip",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Tricep Extensions",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Tricep Extensions: One Arm",  unilateral: true, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
		{name: "Walking Lunges",  unilateral: false, force_bilateral: nil, machine: false, info: "", m_mech_ad_override: nil, f_mech_ad_override: nil, bodyweight: false},
	]
end