def new_exercises
	return [
		{name: "Bench Press: Decline", unilateral: false, machine: false, bodyweight: false},
		{name: "Bench Press: Flat", unilateral: false, machine: false, bodyweight: false},
		{name: "Bench Press: Incline", unilateral: false, machine: false, bodyweight: false},
		{name: "Bent Leg Calf Raises", unilateral: false, machine: true, bodyweight: false},
		{name: "Bicep Curls Preacher/Supported", unilateral: false, machine: false, bodyweight: false},
		{name: "Bicep Curls Reclined", unilateral: true, machine: false, bodyweight: false},
		{name: "Bicep Curls", unilateral: true, machine: false, bodyweight: false},
		{name: "Chest Flies: Incline", unilateral: false, machine: false, bodyweight: false},
		{name: "Chest Flies", unilateral: false, machine: false, bodyweight: false},
		{name: "Chest Press: Decline", unilateral: true, machine: false, bodyweight: false},
		{name: "Chest Press: Flat", unilateral: false, machine: true, bodyweight: false},
		{name: "Chest Press: Incline", unilateral: false, machine: true, bodyweight: false},
		{name: "Chin-ups Plus Weight", unilateral: false, machine: false, bodyweight: true},
		{name: "Chin-ups", unilateral: false, machine: false, bodyweight: true},
		{name: "Clean and Jerks", unilateral: false, machine: false, bodyweight: false},
		{name: "Cleans", unilateral: false, machine: false, bodyweight: true},
		{name: "Dead Lifts", unilateral: true, machine: false, bodyweight: false},
		{name: "Dips Plus Weight", unilateral: false, machine: false, bodyweight: true},
		{name: "Dips", unilateral: false, machine: true, bodyweight: false},
		{name: "Front Raises", unilateral: true, machine: false, bodyweight: false},
		{name: "Front Squats", unilateral: true, machine: false, bodyweight: false},
		{name: "Glute Kick-backs", unilateral: true, machine: true, bodyweight: false},
		{name: "Hammer Bicep Curls", unilateral: true, machine: false, bodyweight: false},
		{name: "Horizontal Rows: Underhanded", unilateral: false, machine: false, bodyweight: false},
		{name: "Horizontal Rows", unilateral: true, machine: false, bodyweight: false},
		{name: "Jerks", unilateral: false, machine: false, bodyweight: true},
		{name: "Jump Lunges", unilateral: true, machine: false, bodyweight: false},
		{name: "Lat Pulldowns", unilateral: true, machine: false, bodyweight: false},
		{name: "Leg Abductions", unilateral: false, machine: true, bodyweight: false},
		{name: "Leg Adductions", unilateral: false, machine: true, bodyweight: false},
		{name: "Leg Extensions", unilateral: false, machine: true, bodyweight: false},
		{name: "Leg Press", unilateral: false, machine: true, bodyweight: false},
		{name: "Lying Leg Curls", unilateral: true, machine: true, bodyweight: false},
		{name: "Narrow Stance Back Squats", unilateral: false, machine: false, bodyweight: true},
		{name: "Narrow Stance Front Squats", unilateral: false, machine: false, bodyweight: true},
		{name: "Parallel-grip Pulldowns Narrow", unilateral: false, machine: true, bodyweight: false},
		{name: "Parallel-grip Pulldowns", unilateral: false, machine: true, bodyweight: false},
		{name: "Pull-ups Plus Weight", unilateral: false, machine: false, bodyweight: true},
		{name: "Pull-ups", unilateral: false, machine: false, bodyweight: true},
		{name: "Pullovers", unilateral: false, machine: true, bodyweight: false},
		{name: "Push-ups Wide", unilateral: false, machine: false, bodyweight: true},
		{name: "Push-ups", unilateral: false, machine: false, bodyweight: true},
		{name: "Reverse Flies", unilateral: false, machine: true, bodyweight: false},
		{name: "Rotators: Anterior Rotation Sagital", unilateral: true, machine: false, bodyweight: false},
		{name: "Rotators: Anterior Rotation Tranverse", unilateral: true, machine: false, bodyweight: false},
		{name: "Rotators: Posterior Rotation Sagital", unilateral: true, machine: false, bodyweight: false},
		{name: "Rotators: Posterior Rotation Tranverse", unilateral: true, machine: false, bodyweight: false},
		{name: "Seated Leg Curls", unilateral: false, machine: true, bodyweight: false},
		{name: "Shoulder Press", unilateral: false, machine: true, bodyweight: false},
		{name: "Shoulder Raises", unilateral: true, machine: false, bodyweight: false},
		{name: "Shoulder Shrugs", unilateral: true, machine: false, bodyweight: false},
		{name: "Squats", unilateral: false, machine: false, bodyweight: true},
		{name: "Stiff Legged Dead Lifts", unilateral: false, machine: false, bodyweight: true},
		{name: "Stiff Legged Dead Lifts", unilateral: true, machine: false, bodyweight: false},
		{name: "Straight Leg Calf Raises", unilateral: false, machine: true, bodyweight: false},
		{name: "Sumo Dead Lifts", unilateral: false, machine: false, bodyweight: true},
		{name: "Triangle Push-ups", unilateral: false, machine: false, bodyweight: true},
		{name: "Tricep Extensions Lying", unilateral: false, machine: false, bodyweight: false},
		{name: "Tricep Extensions Overhead", unilateral: false, machine: false, bodyweight: false},
		{name: "Tricep Extensions Reverse Grip", unilateral: false, machine: false, bodyweight: false},
		{name: "Tricep Extensions", unilateral: false, machine: false, bodyweight: false},
		{name: "Underhand Pulldowns", unilateral: false, machine: true, bodyweight: false},
		{name: "Walking Lunges", unilateral: false, machine: false, bodyweight: true},
	]
end