def session_set_list
  return [
    [1,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [1,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [1,{weight_kg: 50, reps: 8, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [1,{weight_kg: 5, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [1,{weight_kg: 5, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [1,{weight_kg: 5, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [1,{weight_kg: 45, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [1,{weight_kg: 45, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [1,{weight_kg: 45, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [1,{weight_kg: 40, reps: 15, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [2,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [2,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [2,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [2,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [2,{weight_kg: 50, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [2,{weight_kg: 60, reps: 8, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [2,{weight_kg: 14, reps: 8, exercise: Exercise.find_by_name("Hammer Bicep Curls - Dumbbell"), pulley_count: 1}],
    [2,{weight_kg: 14, reps: 8, exercise: Exercise.find_by_name("Hammer Bicep Curls - Dumbbell"), pulley_count: 1}],
    [3,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [3,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [3,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [3,{weight_kg: 140, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [3,{weight_kg: 180, reps: 8, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [3,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Stiff Legged Dead Lifts - Barbell"), pulley_count: 1}],
    [3,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Stiff Legged Dead Lifts - Barbell"), pulley_count: 1}],
    [3,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Stiff Legged Dead Lifts - Barbell"), pulley_count: 1}],
    [4,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [4,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [4,{weight_kg: 50, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [4,{weight_kg: 60, reps: 6, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [4,{weight_kg: 6, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [4,{weight_kg: 6, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [4,{weight_kg: 6, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [4,{weight_kg: 50, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [4,{weight_kg: 50, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [4,{weight_kg: 50, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [4,{weight_kg: 50, reps: 15, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [5,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [5,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [5,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [5,{weight_kg: 50, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [5,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [5,{weight_kg: 70, reps: 8, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [5,{weight_kg: 12, reps: 10, exercise: Exercise.find_by_name("Hammer Bicep Curls - Dumbbell"), pulley_count: 1}],
    [5,{weight_kg: 12, reps: 10, exercise: Exercise.find_by_name("Hammer Bicep Curls - Dumbbell"), pulley_count: 1}],
    [5,{weight_kg: 12, reps: 10, exercise: Exercise.find_by_name("Hammer Bicep Curls - Dumbbell"), pulley_count: 1}],
    [5,{weight_kg: 60, reps: 20, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [6,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [6,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [6,{weight_kg: 160, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [6,{weight_kg: 200, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [6,{weight_kg: 240, reps: 4, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [6,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Stiff Legged Dead Lifts - Barbell"), pulley_count: 1}],
    [6,{weight_kg: 100, reps: 6, exercise: Exercise.find_by_name("Stiff Legged Dead Lifts - Barbell"), pulley_count: 1}],
    [6,{weight_kg: 10, reps: 12, exercise: Exercise.find_by_name("Stiff Legged Dead Lifts - Barbell"), pulley_count: 1}],
    [6,{weight_kg: 80, reps: 15, exercise: Exercise.find_by_name("Straight Leg Calf Raises - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [6,{weight_kg: 80, reps: 15, exercise: Exercise.find_by_name("Straight Leg Calf Raises - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [7,{weight_kg: 50, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [7,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [7,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [7,{weight_kg: 60, reps: 5, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [7,{weight_kg: 7, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [7,{weight_kg: 7, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [7,{weight_kg: 7, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [7,{weight_kg: 55, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [7,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [7,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [8,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [8,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [8,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [8,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [8,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [8,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [8,{weight_kg: 12, reps: 11, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [8,{weight_kg: 12, reps: 11, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [8,{weight_kg: 12, reps: 11, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [8,{weight_kg: 50, reps: 30, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [9,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [9,{weight_kg: 160, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [9,{weight_kg: 200, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [9,{weight_kg: 200, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [9,{weight_kg: 240, reps: 8, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [9,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Stiff Legged Dead Lifts - Barbell"), pulley_count: 1}],
    [9,{weight_kg: 100, reps: 5, exercise: Exercise.find_by_name("Stiff Legged Dead Lifts - Barbell"), pulley_count: 1}],
    [9,{weight_kg: 60, reps: 15, exercise: Exercise.find_by_name("Stiff Legged Dead Lifts - Barbell"), pulley_count: 1}],
    [9,{weight_kg: 80, reps: 20, exercise: Exercise.find_by_name("Straight Leg Calf Raises - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [9,{weight_kg: 80, reps: 20, exercise: Exercise.find_by_name("Straight Leg Calf Raises - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [10,{weight_kg: 50, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [10,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [10,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [10,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [10,{weight_kg: 8, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [10,{weight_kg: 8, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [10,{weight_kg: 8, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [10,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 1}],
    [10,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 1}],
    [10,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 1}],
    [10,{weight_kg: 5, reps: 20, exercise: Exercise.find_by_name("Rotators: Posterior Rotation Tranverse - Cable"), pulley_count: 2}],
    [10,{weight_kg: 5, reps: 20, exercise: Exercise.find_by_name("Rotators: Posterior Rotation Tranverse - Cable"), pulley_count: 2}],
    [10,{weight_kg: 5, reps: 15, exercise: Exercise.find_by_name("Rotators: Posterior Rotation Tranverse - Cable"), pulley_count: 2}],
    [10,{weight_kg: 55, reps: 20, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [11,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [11,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [11,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [11,{weight_kg: 100, reps: 3, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [11,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [11,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [11,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [11,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [11,{weight_kg: 14, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [11,{weight_kg: 14, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [11,{weight_kg: 14, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [11,{weight_kg: 60, reps: 20, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [12,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [12,{weight_kg: 160, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [12,{weight_kg: 200, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [12,{weight_kg: 240, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [12,{weight_kg: 240, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [12,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Stiff Legged Dead Lifts - Barbell"), pulley_count: 1}],
    [12,{weight_kg: 140, reps: 1, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [12,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [12,{weight_kg: 6, reps: 6, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [12,{weight_kg: 100, reps: 20, exercise: Exercise.find_by_name("Straight Leg Calf Raises - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [12,{weight_kg: 100, reps: 20, exercise: Exercise.find_by_name("Straight Leg Calf Raises - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [13,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [13,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [13,{weight_kg: 70, reps: 6, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [13,{weight_kg: 24, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [13,{weight_kg: 24, reps: 7, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [13,{weight_kg: 20, reps: 9, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [13,{weight_kg: 4, reps: 8, exercise: Exercise.find_by_name("Shoulder Raises ~45° - Crossover"), pulley_count: 2}],
    [13,{weight_kg: 3, reps: 13, exercise: Exercise.find_by_name("Shoulder Raises ~45° - Crossover"), pulley_count: 2}],
    [13,{weight_kg: 3, reps: 11, exercise: Exercise.find_by_name("Shoulder Raises ~45° - Crossover"), pulley_count: 2}],
    [13,{weight_kg: 50, reps: 15, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip - Cable"), pulley_count: 2}],
    [13,{weight_kg: 50, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip - Cable"), pulley_count: 2}],
    [13,{weight_kg: 50, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip - Cable"), pulley_count: 2}],
    [13,{weight_kg: 30, reps: 12, exercise: Exercise.find_by_name("Shoulder Press - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [13,{weight_kg: 50, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [14,{weight_kg: 0, reps: 8, exercise: Exercise.find_by_name("Pull-ups - Bodyweight"), pulley_count: 1}],
    [14,{weight_kg: 0, reps: 7, exercise: Exercise.find_by_name("Pull-ups - Bodyweight"), pulley_count: 1}],
    [14,{weight_kg: 0, reps: 5, exercise: Exercise.find_by_name("Pull-ups - Bodyweight"), pulley_count: 1}],
    [14,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [14,{weight_kg: 80, reps: 9, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [14,{weight_kg: 80, reps: 8, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [14,{weight_kg: 70, reps: 15, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [14,{weight_kg: 70, reps: 15, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [14,{weight_kg: 70, reps: 13, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [14,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [14,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [14,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [14,{weight_kg: 14, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [14,{weight_kg: 12, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [14,{weight_kg: 12, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [15,{weight_kg: 60, reps: 6, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [15,{weight_kg: 80, reps: 6, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [15,{weight_kg: 100, reps: 6, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [15,{weight_kg: 120, reps: 6, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [15,{weight_kg: 140, reps: 2, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [15,{weight_kg: 200, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [15,{weight_kg: 240, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [15,{weight_kg: 260, reps: 6, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [15,{weight_kg: 200, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [15,{weight_kg: 200, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [16,{weight_kg: 10, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [16,{weight_kg: 14, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [16,{weight_kg: 16, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [16,{weight_kg: 16, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [16,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [16,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [16,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [16,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [16,{weight_kg: 20, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [16,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [16,{weight_kg: 40, reps: 8, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [16,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [16,{weight_kg: 25, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [16,{weight_kg: 25, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [16,{weight_kg: 25, reps: 8, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [16,{weight_kg: 3, reps: 12, exercise: Exercise.find_by_name("Shoulder Raises ~45° - Crossover"), pulley_count: 2}],
    [16,{weight_kg: 3, reps: 12, exercise: Exercise.find_by_name("Shoulder Raises ~45° - Crossover"), pulley_count: 2}],
    [17,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [17,{weight_kg: 80, reps: 6, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [17,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [17,{weight_kg: 70, reps: 7, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [17,{weight_kg: 26, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [17,{weight_kg: 22, reps: 8, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [17,{weight_kg: 20, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [17,{weight_kg: 7, reps: 15, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [17,{weight_kg: 7, reps: 12, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [17,{weight_kg: 7, reps: 10, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [17,{weight_kg: 60, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip - Cable"), pulley_count: 2}],
    [17,{weight_kg: 55, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip - Cable"), pulley_count: 2}],
    [17,{weight_kg: 50, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip - Cable"), pulley_count: 2}],
    [17,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [18,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [18,{weight_kg: 95, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [18,{weight_kg: 95, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [18,{weight_kg: 95, reps: 8, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [18,{weight_kg: 85, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [18,{weight_kg: 85, reps: 8, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [18,{weight_kg: 85, reps: 9, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [18,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [18,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [18,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [18,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [18,{weight_kg: 35, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [18,{weight_kg: 35, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [18,{weight_kg: 35, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [18,{weight_kg: 12, reps: 12, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [18,{weight_kg: 12, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [18,{weight_kg: 12, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [19,{weight_kg: 16, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [19,{weight_kg: 18, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [19,{weight_kg: 16, reps: 8, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [19,{weight_kg: 16, reps: 8, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [19,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [19,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [19,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [19,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [19,{weight_kg: 30, reps: 15, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [19,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [19,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [19,{weight_kg: 30, reps: 8, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [19,{weight_kg: 40, reps: 12, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [19,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [19,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [19,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [20,{weight_kg: 200, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [20,{weight_kg: 220, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [20,{weight_kg: 240, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [20,{weight_kg: 260, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [20,{weight_kg: 220, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [20,{weight_kg: 220, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [20,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [20,{weight_kg: 100, reps: 8, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [20,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [21,{weight_kg: 25, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [21,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [21,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [21,{weight_kg: 25, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [21,{weight_kg: 16, reps: 8, exercise: Exercise.find_by_name("Bicep Curls Reclined - Dumbbell"), pulley_count: 1}],
    [21,{weight_kg: 14, reps: 9, exercise: Exercise.find_by_name("Bicep Curls Reclined - Dumbbell"), pulley_count: 1}],
    [21,{weight_kg: 12, reps: 10, exercise: Exercise.find_by_name("Bicep Curls Reclined - Dumbbell"), pulley_count: 1}],
    [21,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [21,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [21,{weight_kg: 60, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [21,{weight_kg: 60, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [21,{weight_kg: 25, reps: 15, exercise: Exercise.find_by_name("Bicep Curls - Barbell"), pulley_count: 1}],
    [21,{weight_kg: 25, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Barbell"), pulley_count: 1}],
    [21,{weight_kg: 25, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Barbell"), pulley_count: 1}],
    [22,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [22,{weight_kg: 80, reps: 8, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [22,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [22,{weight_kg: 70, reps: 8, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [22,{weight_kg: 28, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [22,{weight_kg: 24, reps: 9, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [22,{weight_kg: 22, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [22,{weight_kg: 8, reps: 15, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [22,{weight_kg: 8, reps: 12, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [22,{weight_kg: 8, reps: 11, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [22,{weight_kg: 65, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip - Cable"), pulley_count: 2}],
    [22,{weight_kg: 60, reps: 13, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip - Cable"), pulley_count: 2}],
    [22,{weight_kg: 60, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip - Cable"), pulley_count: 2}],
    [22,{weight_kg: 50, reps: 18, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [23,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [23,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [23,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [23,{weight_kg: 100, reps: 9, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [23,{weight_kg: 85, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [23,{weight_kg: 85, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [23,{weight_kg: 85, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [23,{weight_kg: 75, reps: 15, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [23,{weight_kg: 75, reps: 12, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [23,{weight_kg: 75, reps: 10, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [23,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [23,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [23,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [23,{weight_kg: 12, reps: 15, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [23,{weight_kg: 12, reps: 12, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [23,{weight_kg: 12, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [24,{weight_kg: 16, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [24,{weight_kg: 18, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [24,{weight_kg: 18, reps: 8, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [24,{weight_kg: 16, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [24,{weight_kg: 120, reps: 12, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [24,{weight_kg: 120, reps: 12, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [24,{weight_kg: 120, reps: 12, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [24,{weight_kg: 120, reps: 12, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [24,{weight_kg: 40, reps: 12, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [24,{weight_kg: 40, reps: 9, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [24,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [24,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [24,{weight_kg: 45, reps: 12, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [24,{weight_kg: 45, reps: 10, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [24,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [24,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [25,{weight_kg: 60, reps: 6, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [25,{weight_kg: 80, reps: 6, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [25,{weight_kg: 100, reps: 6, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [25,{weight_kg: 80, reps: 8, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [25,{weight_kg: 80, reps: 8, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [25,{weight_kg: 80, reps: 6, exercise: Exercise.find_by_name("Leg Press Sled Unilateral - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [25,{weight_kg: 100, reps: 6, exercise: Exercise.find_by_name("Leg Press Sled Unilateral - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [25,{weight_kg: 100, reps: 6, exercise: Exercise.find_by_name("Leg Press Sled Unilateral - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [25,{weight_kg: 100, reps: 6, exercise: Exercise.find_by_name("Leg Press Sled Unilateral - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [25,{weight_kg: 120, reps: 8, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [25,{weight_kg: 120, reps: 6, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [25,{weight_kg: 100, reps: 12, exercise: Exercise.find_by_name("Dead Lifts - Barbell"), pulley_count: 1}],
    [26,{weight_kg: 25, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [26,{weight_kg: 35, reps: 8, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [26,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [26,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [26,{weight_kg: 25, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [26,{weight_kg: 16, reps: 10, exercise: Exercise.find_by_name("Bicep Curls Reclined - Dumbbell"), pulley_count: 1}],
    [26,{weight_kg: 14, reps: 10, exercise: Exercise.find_by_name("Bicep Curls Reclined - Dumbbell"), pulley_count: 1}],
    [26,{weight_kg: 12, reps: 10, exercise: Exercise.find_by_name("Bicep Curls Reclined - Dumbbell"), pulley_count: 1}],
    [26,{weight_kg: 70, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [26,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [26,{weight_kg: 60, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [26,{weight_kg: 60, reps: 16, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [26,{weight_kg: 27.5, reps: 15, exercise: Exercise.find_by_name("Bicep Curls - Barbell"), pulley_count: 1}],
    [26,{weight_kg: 25, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Barbell"), pulley_count: 1}],
    [26,{weight_kg: 25, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Barbell"), pulley_count: 1}],
    [27,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [27,{weight_kg: 80, reps: 9, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [27,{weight_kg: 70, reps: 11, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [27,{weight_kg: 70, reps: 8, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [27,{weight_kg: 30, reps: 6, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [27,{weight_kg: 28, reps: 5, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [27,{weight_kg: 24, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [27,{weight_kg: 22, reps: 9, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [27,{weight_kg: 9, reps: 15, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [27,{weight_kg: 8, reps: 13, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [27,{weight_kg: 8, reps: 12, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [27,{weight_kg: 70, reps: 11, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [27,{weight_kg: 70, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [27,{weight_kg: 65, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [27,{weight_kg: 50, reps: 18, exercise: Exercise.find_by_name("Chest Press: Flat - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [28,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [28,{weight_kg: 100, reps: 11, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [28,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [28,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [28,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [28,{weight_kg: 85, reps: 11, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [28,{weight_kg: 85, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [28,{weight_kg: 75, reps: 16, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [28,{weight_kg: 75, reps: 13, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [28,{weight_kg: 75, reps: 11, exercise: Exercise.find_by_name("Pulldowns Parallel-grip Wide - Cable"), pulley_count: 1}],
    [28,{weight_kg: 12, reps: 15, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [28,{weight_kg: 12, reps: 15, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [28,{weight_kg: 12, reps: 12, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [28,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [28,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [28,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [29,{weight_kg: 16, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [29,{weight_kg: 18, reps: 11, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [29,{weight_kg: 18, reps: 9, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [29,{weight_kg: 18, reps: 9, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [29,{weight_kg: 130, reps: 10, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [29,{weight_kg: 130, reps: 12, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [29,{weight_kg: 130, reps: 12, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [29,{weight_kg: 130, reps: 12, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [29,{weight_kg: 50, reps: 12, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [29,{weight_kg: 50, reps: 8, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [29,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [29,{weight_kg: 30, reps: 13, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [29,{weight_kg: 45, reps: 12, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [29,{weight_kg: 45, reps: 11, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [29,{weight_kg: 40, reps: 12, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [29,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [30,{weight_kg: 60, reps: 6, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [30,{weight_kg: 80, reps: 8, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [30,{weight_kg: 100, reps: 7, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [30,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [30,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [30,{weight_kg: 100, reps: 8, exercise: Exercise.find_by_name("Leg Press Sled Unilateral - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [30,{weight_kg: 100, reps: 8, exercise: Exercise.find_by_name("Leg Press Sled Unilateral - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [30,{weight_kg: 100, reps: 8, exercise: Exercise.find_by_name("Leg Press Sled Unilateral - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [30,{weight_kg: 100, reps: 8, exercise: Exercise.find_by_name("Leg Press Sled Unilateral - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [31,{weight_kg: 25, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [31,{weight_kg: 35, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [31,{weight_kg: 30, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [31,{weight_kg: 30, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [31,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [31,{weight_kg: 18, reps: 6, exercise: Exercise.find_by_name("Bicep Curls Reclined - Dumbbell"), pulley_count: 1}],
    [31,{weight_kg: 16, reps: 4, exercise: Exercise.find_by_name("Bicep Curls Reclined - Dumbbell"), pulley_count: 1}],
    [31,{weight_kg: 12, reps: 15, exercise: Exercise.find_by_name("Bicep Curls Reclined - Dumbbell"), pulley_count: 1}],
    [31,{weight_kg: 12, reps: 10, exercise: Exercise.find_by_name("Bicep Curls Reclined - Dumbbell"), pulley_count: 1}],
    [31,{weight_kg: 70, reps: 13, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [31,{weight_kg: 70, reps: 11, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [31,{weight_kg: 60, reps: 14, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [31,{weight_kg: 60, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [31,{weight_kg: 30, reps: 14, exercise: Exercise.find_by_name("Bicep Curls - Barbell"), pulley_count: 1}],
    [31,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Barbell"), pulley_count: 1}],
    [31,{weight_kg: 20, reps: 15, exercise: Exercise.find_by_name("Bicep Curls - Barbell"), pulley_count: 1}],
    [32,{weight_kg: 18, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [32,{weight_kg: 28, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [32,{weight_kg: 28, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [32,{weight_kg: 28, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [32,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [32,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [32,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [32,{weight_kg: 24, reps: 11, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [32,{weight_kg: 24, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [32,{weight_kg: 24, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [32,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [32,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [32,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [32,{weight_kg: 20, reps: 20, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [32,{weight_kg: 20, reps: 12, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [32,{weight_kg: 20, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [32,{weight_kg: 90, reps: 15, exercise: Exercise.find_by_name("Pulldowns - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [32,{weight_kg: 90, reps: 12, exercise: Exercise.find_by_name("Pulldowns - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [32,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [33,{weight_kg: 60, reps: 6, exercise: Exercise.find_by_name("Cleans - Barbell"), pulley_count: 1}],
    [33,{weight_kg: 70, reps: 4, exercise: Exercise.find_by_name("Cleans - Barbell"), pulley_count: 1}],
    [33,{weight_kg: 75, reps: 1, exercise: Exercise.find_by_name("Cleans - Barbell"), pulley_count: 1}],
    [33,{weight_kg: 80, reps: 1, exercise: Exercise.find_by_name("Cleans - Barbell"), pulley_count: 1}],
    [34,{weight_kg: 14, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [34,{weight_kg: 18, reps: 11, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [34,{weight_kg: 18, reps: 9, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [34,{weight_kg: 18, reps: 8, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [34,{weight_kg: 25, reps: 25, exercise: Exercise.find_by_name("Shoulder Shrugs - Dumbbell"), pulley_count: 1}],
    [34,{weight_kg: 25, reps: 25, exercise: Exercise.find_by_name("Shoulder Shrugs - Dumbbell"), pulley_count: 1}],
    [34,{weight_kg: 25, reps: 25, exercise: Exercise.find_by_name("Shoulder Shrugs - Dumbbell"), pulley_count: 1}],
    [34,{weight_kg: 52.5, reps: 12, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [34,{weight_kg: 52.5, reps: 11, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [34,{weight_kg: 45, reps: 13, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [34,{weight_kg: 45, reps: 10, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [35,{weight_kg: 60, reps: 6, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [35,{weight_kg: 80, reps: 9, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [35,{weight_kg: 100, reps: 8, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [35,{weight_kg: 80, reps: 12, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [35,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [35,{weight_kg: 240, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [35,{weight_kg: 220, reps: 12, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [35,{weight_kg: 220, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [36,{weight_kg: 18, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [36,{weight_kg: 28, reps: 11, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [36,{weight_kg: 28, reps: 11, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [36,{weight_kg: 28, reps: 9, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [36,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [36,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [36,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [36,{weight_kg: 24, reps: 13, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [36,{weight_kg: 24, reps: 12, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [36,{weight_kg: 24, reps: 8, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [36,{weight_kg: 95, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [36,{weight_kg: 95, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [36,{weight_kg: 95, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [37,{weight_kg: 20, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [37,{weight_kg: 32, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [37,{weight_kg: 32, reps: 9, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [37,{weight_kg: 28, reps: 9, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [37,{weight_kg: 105, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [37,{weight_kg: 105, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [37,{weight_kg: 95, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [37,{weight_kg: 70, reps: 9, exercise: Exercise.find_by_name("Chest Press: Incline - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [37,{weight_kg: 60, reps: 8, exercise: Exercise.find_by_name("Chest Press: Incline - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [37,{weight_kg: 40, reps: 12, exercise: Exercise.find_by_name("Chest Press: Incline - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [37,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [37,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [37,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [38,{weight_kg: 60, reps: 6, exercise: Exercise.find_by_name("Cleans - Barbell"), pulley_count: 1}],
    [38,{weight_kg: 70, reps: 3, exercise: Exercise.find_by_name("Cleans - Barbell"), pulley_count: 1}],
    [38,{weight_kg: 75, reps: 1, exercise: Exercise.find_by_name("Cleans - Barbell"), pulley_count: 1}],
    [38,{weight_kg: 80, reps: 1, exercise: Exercise.find_by_name("Cleans - Barbell"), pulley_count: 1}],
    [39,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [39,{weight_kg: 60, reps: 9, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [39,{weight_kg: 60, reps: 5, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [39,{weight_kg: 50, reps: 4, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [39,{weight_kg: 40, reps: 12, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [39,{weight_kg: 120, reps: 15, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [39,{weight_kg: 120, reps: 15, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [39,{weight_kg: 120, reps: 15, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [39,{weight_kg: 120, reps: 15, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [39,{weight_kg: 50, reps: 15, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [39,{weight_kg: 50, reps: 12, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [39,{weight_kg: 45, reps: 13, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [39,{weight_kg: 45, reps: 13, exercise: Exercise.find_by_name("Shoulder Abductions - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [40,{weight_kg: 20, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Barbell"), pulley_count: 1}],
    [40,{weight_kg: 34, reps: 8, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Barbell"), pulley_count: 1}],
    [40,{weight_kg: 32, reps: 9, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Barbell"), pulley_count: 1}],
    [40,{weight_kg: 30, reps: 9, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Barbell"), pulley_count: 1}],
    [40,{weight_kg: 115, reps: 8, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [40,{weight_kg: 105, reps: 11, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [40,{weight_kg: 95, reps: 12, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [40,{weight_kg: 70, reps: 11, exercise: Exercise.find_by_name("Chest Press: Incline - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [40,{weight_kg: 60, reps: 12, exercise: Exercise.find_by_name("Chest Press: Incline - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [40,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Chest Press: Incline - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [41,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [41,{weight_kg: 80, reps: 11, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [41,{weight_kg: 80, reps: 11, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [41,{weight_kg: 70, reps: 12, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [41,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [41,{weight_kg: 30, reps: 8, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [41,{weight_kg: 24, reps: 13, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [41,{weight_kg: 22, reps: 11, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [41,{weight_kg: 9, reps: 15, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [41,{weight_kg: 8, reps: 13, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [41,{weight_kg: 8, reps: 10, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [42,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [42,{weight_kg: 115, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [42,{weight_kg: 105, reps: 11, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [42,{weight_kg: 105, reps: 9, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [42,{weight_kg: 45, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [42,{weight_kg: 45, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [42,{weight_kg: 45, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [42,{weight_kg: 95, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [42,{weight_kg: 85, reps: 9, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [42,{weight_kg: 75, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [43,{weight_kg: 60, reps: 4, exercise: Exercise.find_by_name("Cleans - Barbell"), pulley_count: 1}],
    [43,{weight_kg: 70, reps: 3, exercise: Exercise.find_by_name("Cleans - Barbell"), pulley_count: 1}],
    [43,{weight_kg: 80, reps: 2, exercise: Exercise.find_by_name("Cleans - Barbell"), pulley_count: 1}],
    [43,{weight_kg: 85, reps: 1, exercise: Exercise.find_by_name("Cleans - Barbell"), pulley_count: 1}],
    [43,{weight_kg: 20, reps: 11, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [43,{weight_kg: 20, reps: 9, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [43,{weight_kg: 20, reps: 7, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [43,{weight_kg: 25, reps: 25, exercise: Exercise.find_by_name("Shoulder Shrugs - Dumbbell"), pulley_count: 1}],
    [43,{weight_kg: 25, reps: 25, exercise: Exercise.find_by_name("Shoulder Shrugs - Dumbbell"), pulley_count: 1}],
    [43,{weight_kg: 25, reps: 25, exercise: Exercise.find_by_name("Shoulder Shrugs - Dumbbell"), pulley_count: 1}],
    [44,{weight_kg: 60, reps: 8, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [45,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [45,{weight_kg: 80, reps: 3, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [45,{weight_kg: 90, reps: 9, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [45,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [45,{weight_kg: 70, reps: 12, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [45,{weight_kg: 30, reps: 9, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [45,{weight_kg: 28, reps: 9, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [45,{weight_kg: 24, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [45,{weight_kg: 22, reps: 13, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [45,{weight_kg: 20, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [45,{weight_kg: 8, reps: 16, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [45,{weight_kg: 8, reps: 12, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [45,{weight_kg: 8, reps: 10, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [46,{weight_kg: 70, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [46,{weight_kg: 120, reps: 8, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [46,{weight_kg: 110, reps: 11, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [46,{weight_kg: 105, reps: 8, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [46,{weight_kg: 95, reps: 8, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [46,{weight_kg: 50, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [46,{weight_kg: 45, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [46,{weight_kg: 45, reps: 12, exercise: Exercise.find_by_name("Horizontal Rows Unilateral - Cable"), pulley_count: 1}],
    [46,{weight_kg: 95, reps: 7, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [46,{weight_kg: 85, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [46,{weight_kg: 65, reps: 12, exercise: Exercise.find_by_name("Horizontal Rows - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [47,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [47,{weight_kg: 70, reps: 7, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [47,{weight_kg: 60, reps: 8, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [47,{weight_kg: 50, reps: 8, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [47,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [47,{weight_kg: 25, reps: 25, exercise: Exercise.find_by_name("Shoulder Shrugs - Dumbbell"), pulley_count: 1}],
    [47,{weight_kg: 25, reps: 25, exercise: Exercise.find_by_name("Shoulder Shrugs - Dumbbell"), pulley_count: 1}],
    [47,{weight_kg: 25, reps: 25, exercise: Exercise.find_by_name("Shoulder Shrugs - Dumbbell"), pulley_count: 1}],
    [47,{weight_kg: 8, reps: 15, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [47,{weight_kg: 8, reps: 13, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [47,{weight_kg: 8, reps: 10, exercise: Exercise.find_by_name("Shoulder Raises - Dumbbell"), pulley_count: 1}],
    [48,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [48,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [48,{weight_kg: 100, reps: 5, exercise: Exercise.find_by_name("Squats - Barbell"), pulley_count: 1}],
    [49,{weight_kg: 50, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [49,{weight_kg: 80, reps: 11, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [49,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [49,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions - Cable"), pulley_count: 2}],
    [49,{weight_kg: 18, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [49,{weight_kg: 18, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [49,{weight_kg: 18, reps: 8, exercise: Exercise.find_by_name("Bicep Curls - Dumbbell"), pulley_count: 1}],
    [49,{weight_kg: 35, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [49,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [49,{weight_kg: 25, reps: 12, exercise: Exercise.find_by_name("Tricep Extensions Reverse Grip Unilateral - Cable"), pulley_count: 2}],
    [49,{weight_kg: 30, reps: 13, exercise: Exercise.find_by_name("Bicep Curls - Barbell"), pulley_count: 1}],
    [49,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Barbell"), pulley_count: 1}],
    [49,{weight_kg: 25, reps: 10, exercise: Exercise.find_by_name("Bicep Curls - Barbell"), pulley_count: 1}],
    [49,{weight_kg: 20, reps: 22, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [50,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [50,{weight_kg: 80, reps: 3, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [50,{weight_kg: 100, reps: 5, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [50,{weight_kg: 90, reps: 8, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [50,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [50,{weight_kg: 70, reps: 13, exercise: Exercise.find_by_name("Bench Press: Flat - Barbell"), pulley_count: 1}],
    [50,{weight_kg: 30, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [50,{weight_kg: 28, reps: 8, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [50,{weight_kg: 24, reps: 10, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [50,{weight_kg: 22, reps: 12, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [50,{weight_kg: 20, reps: 12, exercise: Exercise.find_by_name("Bench Press: Incline Middle - Dumbbell"), pulley_count: 1}],
    [50,{weight_kg: 8, reps: 16, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [50,{weight_kg: 8, reps: 13, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [50,{weight_kg: 8, reps: 11, exercise: Exercise.find_by_name("Butterflies - Crossover"), pulley_count: 2}],
    [51,{weight_kg: 60, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [51,{weight_kg: 90, reps: 11, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [51,{weight_kg: 95, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [51,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows: Parallel-grip - Cable"), pulley_count: 1}],
    [51,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [51,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [51,{weight_kg: 90, reps: 10, exercise: Exercise.find_by_name("Pulldowns - Cable"), pulley_count: 1}],
    [51,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Horizontal Rows - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [51,{weight_kg: 100, reps: 8, exercise: Exercise.find_by_name("Horizontal Rows - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [51,{weight_kg: 100, reps: 8, exercise: Exercise.find_by_name("Horizontal Rows - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [52,{weight_kg: 12, reps: 12, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [52,{weight_kg: 22, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [52,{weight_kg: 20, reps: 9, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [52,{weight_kg: 18, reps: 6, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [52,{weight_kg: 14, reps: 14, exercise: Exercise.find_by_name("Shoulder Press - Dumbbell"), pulley_count: 1}],
    [52,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [52,{weight_kg: 100, reps: 10, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [52,{weight_kg: 120, reps: 12, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [52,{weight_kg: 120, reps: 12, exercise: Exercise.find_by_name("Shoulder Shrugs - Barbell"), pulley_count: 1}],
    [52,{weight_kg: 50, reps: 13, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [52,{weight_kg: 50, reps: 9, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [52,{weight_kg: 40, reps: 10, exercise: Exercise.find_by_name("Shoulder Press - Plate-loaded"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [53,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [53,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [53,{weight_kg: 160, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [53,{weight_kg: 200, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [53,{weight_kg: 240, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [53,{weight_kg: 200, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [53,{weight_kg: 160, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [53,{weight_kg: 120, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
    [53,{weight_kg: 80, reps: 10, exercise: Exercise.find_by_name("Leg Press Sled - Machine"), machine_id: Machine.find_by_name("Placeholder").id, pulley_count: 1}],
  ]
end
